spring:
  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:MyYoutube
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create # 개발환경에서는 편의상 create
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

logging:
  level:
    org.hibernate.SQL: debug

# 운영환경과 다른 개발용 jwt 키 값
jwt:
  key: OewPcNeX7cy++FrTqVsB14Fg8kC9xaphxD9LEdWu170=

# 운영환경과 다른 개발용 동영상 저장 장소
file:
  video: /Users/jeong-youhwan/file
