spring:
  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:MyYoutube
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  data:
    redis:
      port: 6379
      password: 1234
      host: 127.0.0.1
      session:
        store-type: redis

logging:
  level:
    org.hibernate.SQL: debug
